requires = ["tox>=4", "virtualenv"]
env_list = ["format", "type", "3.13", "3.12", "3.11", "3.9", "3.8"]

[gh.python]
"3.13" = ["3.13", "type", "format"]
"3.12" = ["3.12"]
"3.11" = ["3.11"]
"3.10" = ["3.10"]
"3.9" = ["3.9"]
"3.8" = ["3.8"]

[env_run_base]
passenv = ["TF_VERSION"]
setenv = { FORCE_COLOR = "1" }
description = "run unit tests"
deps = ["pytest-xdist", "pytest-sugar"]
commands = [["pytest", "-n", "5", "tests"]]

[env.format]
setenv = { FORCE_COLOR = "1" }
description = "install black in a virtual environment and invoke it on the current folder"
skip_install = true
deps = ["black"]
commands = [["black", { replace = "posargs", default = ["."], extend = true }]]


[env.type]
setenv = { FORCE_COLOR = "1" }
description = "run type checks"
deps = ["mypy"]
commands = [
  [
    "mypy",
    { replace = "posargs", default = [
      "src",
      "tests",
    ], extend = true },
  ],
]

[env."3.13"]
basepython = "python3.13"
inherits = "env_run_base"

[env."3.12"]
basepython = "python3.12"
inherits = "env_run_base"

[env."3.11"]
basepython = "python3.11"
inherits = "env_run_base"

[env."3.9"]
basepython = "python3.9"
inherits = "env_run_base"

[env."3.8"]
basepython = "python3.8"
inherits = "env_run_base"
